import os
import re
import unicodedata
from pathlib import Path

import pandas as pd
import yaml

# Project Root Setup
BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data" / "raw"
CONFIG_DIR = BASE_DIR / "config"
OUTPUT_FILE = CONFIG_DIR / "assets.yaml"

# Category Mapping (File Prefix -> ID Prefix)
CATEGORY_MAP = {
    'mutual': {'prefix': 'mut', 'default_cat': 'mutual_fund'},
    'us':     {'prefix': 'us',  'default_cat': 'stock_us'},
    'domestic': {'prefix': 'jp',  'default_cat': 'stock_jp'},
    'china':  {'prefix': 'cn',  'default_cat': 'stock_cn'},
    'etf_j':  {'prefix': 'etf', 'default_cat': 'etf_jp'},
    'bond':   {'prefix': 'bnd', 'default_cat': 'bond'},
    'reit':   {'prefix': 'reit','default_cat': 'reit'},
    'commodity': {'prefix': 'cmd', 'default_cat': 'commodity'},
    'short_term': {'prefix': 'cash', 'default_cat': 'cash_equivalent'},
}

def normalize_name(text):
    """全角→半角、余計な空白削除"""
    text = unicodedata.normalize('NFKC', text)
    return text.strip()

def generate_id(category_key, raw_name):
    """
    Naming Convention: {cat_prefix}_{slug}_{account}
    """
    prefix = CATEGORY_MAP.get(category_key, {}).get('prefix', 'unk')
    
    # 1. Account Suffix
    suffix = ""
    name_body = raw_name
    if "[NISA]" in raw_name:
        suffix = "_nisa"
        name_body = raw_name.replace("[NISA]", "")
    elif "[特定]" in raw_name:
        suffix = "_toku"
        name_body = raw_name.replace("[特定]", "")
    
    # 2. Slug Generation
    # 英数字以外をアンダースコアに
    normalized = normalize_name(name_body)
    # カッコの中身（ティッカー）があればそれを優先したいが、
    # 汎用性を高めるため全体をスラグ化する
    slug = re.sub(r'[^a-zA-Z0-9]+', '_', normalized).strip('_').lower()
    
    # 短すぎる場合はそのまま、長すぎる場合は適当に切る... 
    # いったんは全部出す。PMが手で直す前提。
    
    return f"{prefix}_{slug}{suffix}"

def extract_assets():
    print(f"[Generator] Scanning CSVs in {DATA_DIR}...")
    
    assets_found = []
    seen_sources = set()

    # Iterate over defined categories
    for filename in os.listdir(DATA_DIR):
        if not filename.endswith(".csv") or filename == "history.csv":
            continue
            
        cat_key = filename.replace(".csv", "")
        if cat_key not in CATEGORY_MAP:
            print(f"[Skip] Unknown category file: {filename}")
            continue

        file_path = DATA_DIR / filename
        try:
            try:
                df = pd.read_csv(file_path, encoding='shift_jis')
            except UnicodeDecodeError:
                df = pd.read_csv(file_path, encoding='utf-8')
            
            # Find Valuation Columns
            # Logic: Contains "評価額(円)" but NOT "時系列" or "前日比"
            target_cols = [c for c in df.columns if '評価額(円)' in c and '時系列' not in c and '前日比' not in c]
            
            print(f"  > {filename}: Found {len(target_cols)} assets.")
            
            for col in target_cols:
                raw_name = col.replace(' 評価額(円)', '')
                
                if raw_name in seen_sources:
                    continue
                
                seen_sources.add(raw_name)
                
                # Generate Metadata
                asset_id = generate_id(cat_key, raw_name)
                display_name = normalize_name(raw_name.replace("[NISA]", "").replace("[特定]", ""))
                default_cat = CATEGORY_MAP[cat_key]['default_cat']
                
                # Color Placeholder (Category based)
                color = "#94a3b8" # Default Slate
                if cat_key == 'mutual': color = "#3b82f6"
                elif cat_key == 'us': color = "#ef4444"
                elif cat_key == 'domestic': color = "#10b981"
                elif cat_key == 'commodity': color = "#eab308"

                assets_found.append({
                    'id': asset_id,
                    'source': raw_name,
                    'name': display_name,
                    'short_name': display_name[:10], # 仮の短縮名
                    'category': default_cat,
                    'color': color
                })
                
        except Exception as e:
            print(f"[Error] Failed to read {filename}: {e}")

    return assets_found

def main():
    assets = extract_assets()
    
    if not assets:
        print("[Warn] No assets found. Check your CSV files.")
        return

    # Create YAML Structure
    yaml_data = {'assets': assets}
    
    os.makedirs(CONFIG_DIR, exist_ok=True)
    
    # Write to file (using safe_dump to avoid python objects)
    # Custom sort needed? -> No, standard list is fine.
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("# ==========================================\n")
        f.write("# THE CAPTION: Asset Catalog\n")
        f.write("# Generated by scripts/dev/generate_asset_yaml.py\n")
        f.write("# ==========================================\n\n")
        yaml.dump(yaml_data, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
        
    print(f"\n[Success] Generated {OUTPUT_FILE}")
    print(f"Total {len(assets)} assets registered.")
    print(">>> Please open the file and CURATE 'name', 'short_name', and 'color'.")

if __name__ == "__main__":
    main()
